# Generated by Django 6.1 on 2026-09-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='お届け先氏名')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=20, verbose_name='都道府県')),
                ('city', models.CharField(max_length=200, verbose_name='市区町村・番地')),
                ('building', models.CharField(blank=True, max_length=200, verbose_name='建物名など')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルトの配送先')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '配送先住所',
                'verbose_name_plural': '配送先住所',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
