# Generated by Django 6.1 on 2026-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_building',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='建物名など'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='', max_length=200, verbose_name='市区町村・番地'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='送料'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(default='', max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_prefecture',
            field=models.CharField(default='', max_length=20, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_recipient_name',
            field=models.CharField(default='', max_length=100, verbose_name='お届け先氏名'),
        ),
    ]
